// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.20.1
// source: mtca.proto

package proto

import (
	proto "github.com/letsencrypt/boulder/core/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Next unused field number: 4
	Pubkey        []byte              `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Identifiers   []*proto.Identifier `protobuf:"bytes,2,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	Profile       string              `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueRequest) Reset() {
	*x = IssueRequest{}
	mi := &file_mtca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRequest) ProtoMessage() {}

func (x *IssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRequest.ProtoReflect.Descriptor instead.
func (*IssueRequest) Descriptor() ([]byte, []int) {
	return file_mtca_proto_rawDescGZIP(), []int{0}
}

func (x *IssueRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *IssueRequest) GetIdentifiers() []*proto.Identifier {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

func (x *IssueRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type IssueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Next unused field number: 4
	MtcLogID      string `protobuf:"bytes,1,opt,name=mtcLogID,proto3" json:"mtcLogID,omitempty"`
	MtcEntryIndex int64  `protobuf:"varint,2,opt,name=mtcEntryIndex,proto3" json:"mtcEntryIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueResponse) Reset() {
	*x = IssueResponse{}
	mi := &file_mtca_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueResponse) ProtoMessage() {}

func (x *IssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mtca_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueResponse.ProtoReflect.Descriptor instead.
func (*IssueResponse) Descriptor() ([]byte, []int) {
	return file_mtca_proto_rawDescGZIP(), []int{1}
}

func (x *IssueResponse) GetMtcLogID() string {
	if x != nil {
		return x.MtcLogID
	}
	return ""
}

func (x *IssueResponse) GetMtcEntryIndex() int64 {
	if x != nil {
		return x.MtcEntryIndex
	}
	return 0
}

var File_mtca_proto protoreflect.FileDescriptor

var file_mtca_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x6d, 0x74, 0x63, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x74,
	0x63, 0x61, 0x1a, 0x15, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a, 0x0c, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x12, 0x32, 0x0a, 0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22,
	0x51, 0x0a, 0x0d, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x74, 0x63, 0x4c, 0x6f, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x74, 0x63, 0x4c, 0x6f, 0x67, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d,
	0x6d, 0x74, 0x63, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x6d, 0x74, 0x63, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x32, 0x3a, 0x0a, 0x04, 0x4d, 0x54, 0x43, 0x41, 0x12, 0x32, 0x0a, 0x05, 0x49, 0x73,
	0x73, 0x75, 0x65, 0x12, 0x12, 0x2e, 0x6d, 0x74, 0x63, 0x61, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x74, 0x63, 0x61, 0x2e, 0x49,
	0x73, 0x73, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2b,
	0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x74,
	0x73, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2f, 0x62, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72,
	0x2f, 0x6d, 0x74, 0x63, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_mtca_proto_rawDescOnce sync.Once
	file_mtca_proto_rawDescData []byte
)

func file_mtca_proto_rawDescGZIP() []byte {
	file_mtca_proto_rawDescOnce.Do(func() {
		file_mtca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mtca_proto_rawDesc), len(file_mtca_proto_rawDesc)))
	})
	return file_mtca_proto_rawDescData
}

var file_mtca_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mtca_proto_goTypes = []any{
	(*IssueRequest)(nil),     // 0: mtca.IssueRequest
	(*IssueResponse)(nil),    // 1: mtca.IssueResponse
	(*proto.Identifier)(nil), // 2: core.Identifier
}
var file_mtca_proto_depIdxs = []int32{
	2, // 0: mtca.IssueRequest.identifiers:type_name -> core.Identifier
	0, // 1: mtca.MTCA.Issue:input_type -> mtca.IssueRequest
	1, // 2: mtca.MTCA.Issue:output_type -> mtca.IssueResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mtca_proto_init() }
func file_mtca_proto_init() {
	if File_mtca_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mtca_proto_rawDesc), len(file_mtca_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mtca_proto_goTypes,
		DependencyIndexes: file_mtca_proto_depIdxs,
		MessageInfos:      file_mtca_proto_msgTypes,
	}.Build()
	File_mtca_proto = out.File
	file_mtca_proto_goTypes = nil
	file_mtca_proto_depIdxs = nil
}
