# https://github.com/rubenv/sql-migrate#readme
boulder_sa_test:
  dialect: mysql
  datasource: root@tcp(boulder-vitess:33577)/boulder_sa_test?parseTime=true&max_execution_time=13000&long_query_time=11
  dir: boulder_sa

boulder_sa_integration:
  dialect: mysql
  datasource: root@tcp(boulder-vitess:33577)/boulder_sa_integration?parseTime=true&max_execution_time=13000&long_query_time=11
  dir: boulder_sa

incidents_sa_test:
  dialect: mysql
  datasource: root@tcp(boulder-vitess:33577)/incidents_sa_test?parseTime=true&max_execution_time=13000&long_query_time=11
  dir: incidents_sa

incidents_sa_integration:
  dialect: mysql
  datasource: root@tcp(boulder-vitess:33577)/incidents_sa_integration?parseTime=true&max_execution_time=13000&long_query_time=11
  dir: incidents_sa
