# https://github.com/rubenv/sql-migrate#readme
boulder_sa_test:
  dialect: mysql
  datasource: root@tcp(boulder-proxysql:6033)/boulder_sa_test?parseTime=true
  dir: boulder_sa

boulder_sa_integration:
  dialect: mysql
  datasource: root@tcp(boulder-proxysql:6033)/boulder_sa_integration?parseTime=true
  dir: boulder_sa

incidents_sa_test:
  dialect: mysql
  datasource: root@tcp(boulder-proxysql:6033)/incidents_sa_test?parseTime=true
  dir: incidents_sa

incidents_sa_integration:
  dialect: mysql
  datasource: root@tcp(boulder-proxysql:6033)/incidents_sa_integration?parseTime=true
  dir: incidents_sa
