dist: bin

builds:
  - id: boulder-build
    main: ./cmd/boulder
    binary: boulder
    goarch:
        - amd64
        # - arm64
    goos:
        - linux
        # - darwin
    goarm:
      - "6"
      - "7"
    ldflags:
      - -X "github.com/letsencrypt/boulder/core.BuildID={{ .ShortCommit }}"
      - -X "github.com/letsencrypt/boulder/core.BuildHost={{ .Env.USER }}@{{ .Env.HOSTNAME }}"
      - -X "github.com/letsencrypt/boulder/core.BuildTime={{ .Date }}"
    hooks:
      post: ./link.sh {{ .Path }}
    flags:
      - -mod=vendor

nfpms:
  - id: boulder-nfpm
    package_name: boulder
    builds:
      - boulder-build
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Let's Encrypt <opensource@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/
    contents:
      - &c
        src: boulder
        dst: /opt/boulder/bin/admin-revoker
        type: symlink
      - <<: *c
        dst: /opt/boulder/bin/akamai-purger
      - <<: *c
        dst: /opt/boulder/bin/bad-key-revoker
      - <<: *c
        dst: /opt/boulder/bin/boulder-ca
      - <<: *c
        dst: /opt/boulder/bin/boulder-observer
      - <<: *c
        dst: /opt/boulder/bin/boulder-publisher
      - <<: *c
        dst: /opt/boulder/bin/boulder-ra
      - <<: *c
        dst: /opt/boulder/bin/boulder-remoteva
      - <<: *c
        dst: /opt/boulder/bin/boulder-sa
      - <<: *c
        dst: /opt/boulder/bin/boulder-va
      - <<: *c
        dst: /opt/boulder/bin/boulder-wfe
      - <<: *c
        dst: /opt/boulder/bin/boulder-wfe2
      - <<: *c
        dst: /opt/boulder/bin/caa-log-checker
      - <<: *c
        dst: /opt/boulder/bin/ceremony
      - <<: *c
        dst: /opt/boulder/bin/cert-checker
      - <<: *c
        dst: /opt/boulder/bin/contact-auditor
      - <<: *c
        dst: /opt/boulder/bin/expiration-mailer
      - <<: *c
        dst: /opt/boulder/bin/id-exporter
      - <<: *c
        dst: /opt/boulder/bin/log-validator
      - <<: *c
        dst: /opt/boulder/bin/nonce-service
      - <<: *c
        dst: /opt/boulder/bin/notify-mailer
      - <<: *c
        dst: /opt/boulder/bin/ocsp-responder
      - <<: *c
        dst: /opt/boulder/bin/ocsp-updater
      - <<: *c
        dst: /opt/boulder/bin/orphan-finder
      - <<: *c
        dst: /opt/boulder/bin/reversed-hostname-checker
      - <<: *c
        dst: /opt/boulder/bin/rocsp-tool
