# https://goreleaser.com/customization/build
builds:
  - id: "boulder-build"
    main: ./cmd/boulder
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - GOFLAGS=-mod=vendor
    binary: "boulder"
    goos:
      - linux
    goarch:
      - amd64

# https://goreleaser.com/customization/checksum
checksum:
  name_template: "checksums.txt"

# https://goreleaser.com/customization/changelog
changelog:
  skip: true

# https://goreleaser.com/customization/archive
archives:
  - replacements:
      amd64: x86_64

# https://goreleaser.com/customization/nfpm
nfpms:
  - id: boulder-nfpm
    package_name: boulder
    builds:
      - boulder-build
    maintainer: boulder <boulder@letsencrypt.org>
    vendor: ISRG
    homepage: https://letsencrypt.org
    replacements:
      amd64: x86_64
    formats:
      - deb
