builds:
  - id: admin-revoker
    main: ./cmd/admin-revoker
    binary: admin-revoker
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: akamai-purger
    main: ./cmd/akamai-purger
    binary: akamai-purger
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: bad-key-revoker
    main: ./cmd/bad-key-revoker
    binary: bad-key-revoker
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: boulder-ca
    main: ./cmd/boulder-ca
    binary: boulder-ca
    goarch:
        - amd64
    goos:
        - linux

  - id: boulder-observer
    main: ./cmd/boulder-observer
    binary: boulder-observer
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: boulder-publisher
    main: ./cmd/boulder-publisher
    binary: boulder-publisher
    goarch:
        - amd64
    goos:
        - linux

  - id: boulder-ra
    main: ./cmd/boulder-ra
    binary: boulder-ra
    goarch:
        - amd64
    goos:
        - linux

  - id: boulder-sa
    main: ./cmd/boulder-sa
    binary: boulder-sa
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: boulder-va
    main: ./cmd/boulder-va
    binary: boulder-va
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: boulder-wfe
    main: ./cmd/boulder-wfe
    binary: boulder-wfe
    goarch:
        - amd64
    goos:
        - linux

  - id: boulder-wfe2
    main: ./cmd/boulder-wfe2
    binary: boulder-wfe2
    goarch:
        - amd64
    goos:
        - linux

  - id: caa-log-checker
    main: ./cmd/caa-log-checker
    binary: caa-log-checker
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: ceremony
    main: ./cmd/ceremony
    binary: ceremony
    goarch:
        - amd64
    goos:
        - linux

  - id: cert-checker
    main: ./cmd/cert-checker
    binary: cert-checker
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: contact-auditor
    main: ./cmd/contact-auditor
    binary: contact-auditor
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: expiration-mailer
    main: ./cmd/expiration-mailer
    binary: expiration-mailer
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: id-exporter
    main: ./cmd/id-exporter
    binary: id-exporter
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: log-validator
    main: ./cmd/log-validator
    binary: log-validator
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: nonce-service
    main: ./cmd/nonce-service
    binary: nonce-service
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: notify-mailer
    main: ./cmd/notify-mailer
    binary: notify-mailer
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: ocsp-responder
    main: ./cmd/ocsp-responder
    binary: ocsp-responder
    goarch:
        - amd64
    goos:
        - linux

  - id: ocsp-updater
    main: ./cmd/ocsp-updater
    binary: ocsp-updater
    goarch:
        - amd64
    env:
        - CGO_ENABLED=0
    goos:
        - linux

  - id: orphan-finder
    main: ./cmd/orphan-finder
    binary: orphan-finder
    goarch:
        - amd64
    goos:
        - linux

nfpms:
  - id: admin-revoker-package
    package_name: boulder-admin-revoker
    builds:
      - admin-revoker
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: akamai-purger-package
    package_name: boulder-akamai-purger
    builds:
      - akamai-purger
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: bad-key-revoker-package
    package_name: boulder-bad-key-revoker
    builds:
      - bad-key-revoker
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: boulder-ca-package
    package_name: boulder-ca
    builds:
      - boulder-ca
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: boulder-observer-package
    package_name: boulder-observer
    builds:
      - boulder-observer
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: boulder-publisher-package
    package_name: boulder-publisher
    builds:
      - boulder-publisher
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: boulder-ra-package
    package_name: boulder-ra
    builds:
      - boulder-ra
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: boulder-sa-package
    package_name: boulder-sa
    builds:
      - boulder-sa
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: boulder-va-package
    package_name: boulder-va
    builds:
      - boulder-va
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: boulder-wfe-package
    package_name: boulder-wfe
    builds:
      - boulder-wfe
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: boulder-wfe2-package
    package_name: boulder-wfe2
    builds:
      - boulder-wfe2
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: caa-log-checker-package
    package_name: boulder-caa-log-checker
    builds:
      - caa-log-checker
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: ceremony-package
    package_name: boulder-ceremony
    builds:
      - ceremony
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: cert-checker-package
    package_name: boulder-cert-checker
    builds:
      - cert-checker
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: contact-auditor-package
    package_name: boulder-contact-auditor
    builds:
      - contact-auditor
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: expiration-mailer-package
    package_name: boulder-expiration-mailer
    builds:
      - expiration-mailer
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: id-exporter-package
    package_name: boulder-id-exporter
    builds:
      - id-exporter
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: log-validator-package
    package_name: boulder-log-validator
    builds:
      - log-validator
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: nonce-service-package
    package_name: boulder-nonce-service
    builds:
      - nonce-service
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: notify-mailer-package
    package_name: boulder-notify-mailer
    builds:
      - notify-mailer
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: ocsp-responder-package
    package_name: boulder-ocsp-responder
    builds:
      - ocsp-responder
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: ocsp-updater-package
    package_name: boulder-ocsp-updater
    builds:
      - ocsp-updater
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/

  - id: orphan-finder-package
    package_name: boulder-orphan-finder
    builds:
      - orphan-finder
    formats:
      - rpm
      - deb
    bindir: /opt/boulder/bin
    maintainer: Boulder <boulder@letsencrypt.org>
    vendor: Let's Encrypt
    homepage: https://letsencrypt.org/
