version: '3'
services:
  boulder:
    environment:
      FAKE_DNS: 10.77.77.77
      BOULDER_CONFIG_DIR: &boulder_config_dir test/config-next
      GOFLAGS: -mod=vendor
  # TODO(#6517): remove bredis_clusterer
  bredis_clusterer:
    depends_on:
      - bredis_7
      - bredis_8
  # TODO(#6517): move both nodes to docker-compose.yml
  bredis_7:
    image: redis:6.2.7
    volumes:
      - ./test/:/test/:cached
    command: redis-server /test/redis.config
    networks:
      redisnet:
        ipv4_address: 10.33.33.8

  bredis_8:
    image: redis:6.2.7
    volumes:
      - ./test/:/test/:cached
    command: redis-server /test/redis.config
    networks:
      redisnet:
        ipv4_address: 10.33.33.9
