FROM golang:1.6

RUN apt-get update && apt-get install -y libltdl-dev ruby ruby-dev build-essential rpm && \
    gem install fpm && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


COPY . /go/src/github.com/letsencrypt/boulder
RUN mkdir /tmp/boulder-build
WORKDIR /go/src/github.com/letsencrypt/boulder
CMD [ "make", "rpm" ]
