// Code generated by protoc-gen-go.
// source: core/proto/core.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	core/proto/core.proto

It has these top-level messages:
	Challenge
	ValidationRecord
	ProblemDetails
	Certificate
	Registration
	Authorization
	Order
	Empty
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Challenge struct {
	Id                *int64              `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type              *string             `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Status            *string             `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
	Uri               *string             `protobuf:"bytes,9,opt,name=uri" json:"uri,omitempty"`
	Token             *string             `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	KeyAuthorization  *string             `protobuf:"bytes,5,opt,name=keyAuthorization" json:"keyAuthorization,omitempty"`
	Validationrecords []*ValidationRecord `protobuf:"bytes,10,rep,name=validationrecords" json:"validationrecords,omitempty"`
	Error             *ProblemDetails     `protobuf:"bytes,7,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized  []byte              `json:"-"`
}

func (m *Challenge) Reset()                    { *m = Challenge{} }
func (m *Challenge) String() string            { return proto1.CompactTextString(m) }
func (*Challenge) ProtoMessage()               {}
func (*Challenge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Challenge) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Challenge) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Challenge) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *Challenge) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *Challenge) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Challenge) GetKeyAuthorization() string {
	if m != nil && m.KeyAuthorization != nil {
		return *m.KeyAuthorization
	}
	return ""
}

func (m *Challenge) GetValidationrecords() []*ValidationRecord {
	if m != nil {
		return m.Validationrecords
	}
	return nil
}

func (m *Challenge) GetError() *ProblemDetails {
	if m != nil {
		return m.Error
	}
	return nil
}

type ValidationRecord struct {
	Hostname          *string  `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Port              *string  `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	AddressesResolved [][]byte `protobuf:"bytes,3,rep,name=addressesResolved" json:"addressesResolved,omitempty"`
	AddressUsed       []byte   `protobuf:"bytes,4,opt,name=addressUsed" json:"addressUsed,omitempty"`
	Authorities       []string `protobuf:"bytes,5,rep,name=authorities" json:"authorities,omitempty"`
	Url               *string  `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
	// A list of addresses tried before the address used (see
	// core/objects.go and the comment on the ValidationRecord structure
	// definition for more information.
	AddressesTried   [][]byte `protobuf:"bytes,7,rep,name=addressesTried" json:"addressesTried,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ValidationRecord) Reset()                    { *m = ValidationRecord{} }
func (m *ValidationRecord) String() string            { return proto1.CompactTextString(m) }
func (*ValidationRecord) ProtoMessage()               {}
func (*ValidationRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ValidationRecord) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *ValidationRecord) GetPort() string {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return ""
}

func (m *ValidationRecord) GetAddressesResolved() [][]byte {
	if m != nil {
		return m.AddressesResolved
	}
	return nil
}

func (m *ValidationRecord) GetAddressUsed() []byte {
	if m != nil {
		return m.AddressUsed
	}
	return nil
}

func (m *ValidationRecord) GetAuthorities() []string {
	if m != nil {
		return m.Authorities
	}
	return nil
}

func (m *ValidationRecord) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *ValidationRecord) GetAddressesTried() [][]byte {
	if m != nil {
		return m.AddressesTried
	}
	return nil
}

type ProblemDetails struct {
	ProblemType      *string `protobuf:"bytes,1,opt,name=problemType" json:"problemType,omitempty"`
	Detail           *string `protobuf:"bytes,2,opt,name=detail" json:"detail,omitempty"`
	HttpStatus       *int32  `protobuf:"varint,3,opt,name=httpStatus" json:"httpStatus,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProblemDetails) Reset()                    { *m = ProblemDetails{} }
func (m *ProblemDetails) String() string            { return proto1.CompactTextString(m) }
func (*ProblemDetails) ProtoMessage()               {}
func (*ProblemDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProblemDetails) GetProblemType() string {
	if m != nil && m.ProblemType != nil {
		return *m.ProblemType
	}
	return ""
}

func (m *ProblemDetails) GetDetail() string {
	if m != nil && m.Detail != nil {
		return *m.Detail
	}
	return ""
}

func (m *ProblemDetails) GetHttpStatus() int32 {
	if m != nil && m.HttpStatus != nil {
		return *m.HttpStatus
	}
	return 0
}

type Certificate struct {
	RegistrationID   *int64  `protobuf:"varint,1,opt,name=registrationID" json:"registrationID,omitempty"`
	Serial           *string `protobuf:"bytes,2,opt,name=serial" json:"serial,omitempty"`
	Digest           *string `protobuf:"bytes,3,opt,name=digest" json:"digest,omitempty"`
	Der              []byte  `protobuf:"bytes,4,opt,name=der" json:"der,omitempty"`
	Issued           *int64  `protobuf:"varint,5,opt,name=issued" json:"issued,omitempty"`
	Expires          *int64  `protobuf:"varint,6,opt,name=expires" json:"expires,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Certificate) Reset()                    { *m = Certificate{} }
func (m *Certificate) String() string            { return proto1.CompactTextString(m) }
func (*Certificate) ProtoMessage()               {}
func (*Certificate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Certificate) GetRegistrationID() int64 {
	if m != nil && m.RegistrationID != nil {
		return *m.RegistrationID
	}
	return 0
}

func (m *Certificate) GetSerial() string {
	if m != nil && m.Serial != nil {
		return *m.Serial
	}
	return ""
}

func (m *Certificate) GetDigest() string {
	if m != nil && m.Digest != nil {
		return *m.Digest
	}
	return ""
}

func (m *Certificate) GetDer() []byte {
	if m != nil {
		return m.Der
	}
	return nil
}

func (m *Certificate) GetIssued() int64 {
	if m != nil && m.Issued != nil {
		return *m.Issued
	}
	return 0
}

func (m *Certificate) GetExpires() int64 {
	if m != nil && m.Expires != nil {
		return *m.Expires
	}
	return 0
}

type Registration struct {
	Id               *int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Key              []byte   `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Contact          []string `protobuf:"bytes,3,rep,name=contact" json:"contact,omitempty"`
	ContactsPresent  *bool    `protobuf:"varint,4,opt,name=contactsPresent" json:"contactsPresent,omitempty"`
	Agreement        *string  `protobuf:"bytes,5,opt,name=agreement" json:"agreement,omitempty"`
	InitialIP        []byte   `protobuf:"bytes,6,opt,name=initialIP" json:"initialIP,omitempty"`
	CreatedAt        *int64   `protobuf:"varint,7,opt,name=createdAt" json:"createdAt,omitempty"`
	Status           *string  `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Registration) Reset()                    { *m = Registration{} }
func (m *Registration) String() string            { return proto1.CompactTextString(m) }
func (*Registration) ProtoMessage()               {}
func (*Registration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Registration) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Registration) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Registration) GetContact() []string {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *Registration) GetContactsPresent() bool {
	if m != nil && m.ContactsPresent != nil {
		return *m.ContactsPresent
	}
	return false
}

func (m *Registration) GetAgreement() string {
	if m != nil && m.Agreement != nil {
		return *m.Agreement
	}
	return ""
}

func (m *Registration) GetInitialIP() []byte {
	if m != nil {
		return m.InitialIP
	}
	return nil
}

func (m *Registration) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *Registration) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

type Authorization struct {
	Id             *string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Identifier     *string      `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	RegistrationID *int64       `protobuf:"varint,3,opt,name=registrationID" json:"registrationID,omitempty"`
	Status         *string      `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Expires        *int64       `protobuf:"varint,5,opt,name=expires" json:"expires,omitempty"`
	Challenges     []*Challenge `protobuf:"bytes,6,rep,name=challenges" json:"challenges,omitempty"`
	Combinations   []byte       `protobuf:"bytes,7,opt,name=combinations" json:"combinations,omitempty"`
	// authz2 specific fields
	// TODO: these fields are not currently populated by anything
	V2               *bool    `protobuf:"varint,8,opt,name=v2" json:"v2,omitempty"`
	Token            []byte   `protobuf:"bytes,9,opt,name=token" json:"token,omitempty"`
	ChallengeTypes   []string `protobuf:"bytes,10,rep,name=challengeTypes" json:"challengeTypes,omitempty"`
	Attempted        *string  `protobuf:"bytes,11,opt,name=attempted" json:"attempted,omitempty"`
	ValidationError  []byte   `protobuf:"bytes,12,opt,name=validationError" json:"validationError,omitempty"`
	ValidationRecord []byte   `protobuf:"bytes,13,opt,name=validationRecord" json:"validationRecord,omitempty"`
	IdentifierType   *string  `protobuf:"bytes,14,opt,name=identifierType" json:"identifierType,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Authorization) Reset()                    { *m = Authorization{} }
func (m *Authorization) String() string            { return proto1.CompactTextString(m) }
func (*Authorization) ProtoMessage()               {}
func (*Authorization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Authorization) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Authorization) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *Authorization) GetRegistrationID() int64 {
	if m != nil && m.RegistrationID != nil {
		return *m.RegistrationID
	}
	return 0
}

func (m *Authorization) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *Authorization) GetExpires() int64 {
	if m != nil && m.Expires != nil {
		return *m.Expires
	}
	return 0
}

func (m *Authorization) GetChallenges() []*Challenge {
	if m != nil {
		return m.Challenges
	}
	return nil
}

func (m *Authorization) GetCombinations() []byte {
	if m != nil {
		return m.Combinations
	}
	return nil
}

func (m *Authorization) GetV2() bool {
	if m != nil && m.V2 != nil {
		return *m.V2
	}
	return false
}

func (m *Authorization) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Authorization) GetChallengeTypes() []string {
	if m != nil {
		return m.ChallengeTypes
	}
	return nil
}

func (m *Authorization) GetAttempted() string {
	if m != nil && m.Attempted != nil {
		return *m.Attempted
	}
	return ""
}

func (m *Authorization) GetValidationError() []byte {
	if m != nil {
		return m.ValidationError
	}
	return nil
}

func (m *Authorization) GetValidationRecord() []byte {
	if m != nil {
		return m.ValidationRecord
	}
	return nil
}

func (m *Authorization) GetIdentifierType() string {
	if m != nil && m.IdentifierType != nil {
		return *m.IdentifierType
	}
	return ""
}

type Order struct {
	Id                *int64          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	RegistrationID    *int64          `protobuf:"varint,2,opt,name=registrationID" json:"registrationID,omitempty"`
	Expires           *int64          `protobuf:"varint,3,opt,name=expires" json:"expires,omitempty"`
	Error             *ProblemDetails `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	CertificateSerial *string         `protobuf:"bytes,5,opt,name=certificateSerial" json:"certificateSerial,omitempty"`
	Authorizations    []string        `protobuf:"bytes,6,rep,name=authorizations" json:"authorizations,omitempty"`
	Status            *string         `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
	Names             []string        `protobuf:"bytes,8,rep,name=names" json:"names,omitempty"`
	BeganProcessing   *bool           `protobuf:"varint,9,opt,name=beganProcessing" json:"beganProcessing,omitempty"`
	Created           *int64          `protobuf:"varint,10,opt,name=created" json:"created,omitempty"`
	XXX_unrecognized  []byte          `json:"-"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto1.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Order) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Order) GetRegistrationID() int64 {
	if m != nil && m.RegistrationID != nil {
		return *m.RegistrationID
	}
	return 0
}

func (m *Order) GetExpires() int64 {
	if m != nil && m.Expires != nil {
		return *m.Expires
	}
	return 0
}

func (m *Order) GetError() *ProblemDetails {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Order) GetCertificateSerial() string {
	if m != nil && m.CertificateSerial != nil {
		return *m.CertificateSerial
	}
	return ""
}

func (m *Order) GetAuthorizations() []string {
	if m != nil {
		return m.Authorizations
	}
	return nil
}

func (m *Order) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *Order) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Order) GetBeganProcessing() bool {
	if m != nil && m.BeganProcessing != nil {
		return *m.BeganProcessing
	}
	return false
}

func (m *Order) GetCreated() int64 {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return 0
}

type Empty struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto1.RegisterType((*Challenge)(nil), "core.Challenge")
	proto1.RegisterType((*ValidationRecord)(nil), "core.ValidationRecord")
	proto1.RegisterType((*ProblemDetails)(nil), "core.ProblemDetails")
	proto1.RegisterType((*Certificate)(nil), "core.Certificate")
	proto1.RegisterType((*Registration)(nil), "core.Registration")
	proto1.RegisterType((*Authorization)(nil), "core.Authorization")
	proto1.RegisterType((*Order)(nil), "core.Order")
	proto1.RegisterType((*Empty)(nil), "core.Empty")
}

func init() { proto1.RegisterFile("core/proto/core.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 801 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0x05, 0x45, 0x31, 0x12, 0x47, 0x8c, 0xe2, 0x2c, 0xdc, 0x60, 0x51, 0x14, 0x01, 0xc1, 0x43,
	0x40, 0x04, 0x45, 0x0c, 0xf8, 0x0f, 0xd2, 0x38, 0x87, 0x9c, 0x6a, 0x6c, 0xd2, 0x1e, 0x7a, 0xa3,
	0xc9, 0xa9, 0xbc, 0x35, 0x45, 0x12, 0xbb, 0x6b, 0xa1, 0xea, 0x3f, 0xf4, 0x43, 0xfa, 0x31, 0xbd,
	0xf7, 0x0b, 0x7a, 0xec, 0x37, 0x14, 0x33, 0x4b, 0x89, 0x14, 0xe5, 0xa2, 0xb7, 0x99, 0xb7, 0x23,
	0xee, 0xec, 0xbc, 0x37, 0x4f, 0xf0, 0x55, 0xd9, 0x1a, 0xbc, 0xea, 0x4c, 0xeb, 0xda, 0x2b, 0x0a,
	0xdf, 0x71, 0x28, 0xe6, 0x14, 0x67, 0xbf, 0xcf, 0x20, 0xfe, 0x70, 0x5f, 0xd4, 0x35, 0x36, 0x1b,
	0x14, 0x6b, 0x98, 0xe9, 0x4a, 0x06, 0x69, 0x90, 0x87, 0x6a, 0xa6, 0x2b, 0x21, 0x60, 0xee, 0xf6,
	0x1d, 0xca, 0x59, 0x1a, 0xe4, 0xb1, 0xe2, 0x58, 0xbc, 0x82, 0x67, 0xd6, 0x15, 0xee, 0xd1, 0xca,
	0x67, 0x8c, 0xf6, 0x99, 0xb8, 0x80, 0xf0, 0xd1, 0x68, 0x19, 0x33, 0x48, 0xa1, 0xb8, 0x84, 0xc8,
	0xb5, 0x0f, 0xd8, 0xc8, 0x90, 0x31, 0x9f, 0x88, 0xb7, 0x70, 0xf1, 0x80, 0xfb, 0xf7, 0x8f, 0xee,
	0xbe, 0x35, 0xfa, 0xb7, 0xc2, 0xe9, 0xb6, 0x91, 0x11, 0x17, 0x9c, 0xe1, 0xe2, 0x06, 0x5e, 0xee,
	0x8a, 0x5a, 0x57, 0x9c, 0x19, 0x2c, 0x5b, 0x53, 0x59, 0x09, 0x69, 0x98, 0xaf, 0xae, 0x5f, 0xbd,
	0xe3, 0xb7, 0xfc, 0x78, 0x3c, 0x56, 0x7c, 0xac, 0xce, 0x7f, 0x20, 0xde, 0x42, 0x84, 0xc6, 0xb4,
	0x46, 0x2e, 0xd2, 0x20, 0x5f, 0x5d, 0x5f, 0xfa, 0x5f, 0xde, 0x9a, 0xf6, 0xae, 0xc6, 0xed, 0x0d,
	0xba, 0x42, 0xd7, 0x56, 0xf9, 0x92, 0xec, 0x9f, 0x00, 0x2e, 0xa6, 0xdf, 0x14, 0x5f, 0xc3, 0xf2,
	0xbe, 0xb5, 0xae, 0x29, 0xb6, 0xc8, 0xc3, 0x89, 0xd5, 0x31, 0xa7, 0x11, 0x75, 0xad, 0x71, 0x87,
	0x11, 0x51, 0x2c, 0xbe, 0x85, 0x97, 0x45, 0x55, 0x19, 0xb4, 0x16, 0xad, 0x42, 0xdb, 0xd6, 0x3b,
	0xac, 0x64, 0x98, 0x86, 0x79, 0xa2, 0xce, 0x0f, 0x44, 0x0a, 0xab, 0x1e, 0xfc, 0xc1, 0x62, 0x25,
	0xe7, 0x69, 0x90, 0x27, 0x6a, 0x0c, 0x71, 0x85, 0x9f, 0x8b, 0xd3, 0x68, 0x65, 0x94, 0x86, 0x79,
	0xac, 0xc6, 0x90, 0x1f, 0x7e, 0xdd, 0x33, 0x42, 0xa1, 0x78, 0x03, 0xeb, 0xe3, 0x55, 0x5f, 0x8c,
	0xc6, 0x4a, 0x2e, 0xb8, 0x81, 0x09, 0x9a, 0xfd, 0x02, 0xeb, 0xd3, 0x49, 0xd0, 0x6d, 0x9d, 0x47,
	0xbe, 0x10, 0xf7, 0xfe, 0xc1, 0x63, 0x88, 0x24, 0x50, 0x71, 0x71, 0xff, 0xea, 0x3e, 0x13, 0xaf,
	0x01, 0xee, 0x9d, 0xeb, 0x3e, 0x7b, 0x79, 0x10, 0xeb, 0x91, 0x1a, 0x21, 0xd9, 0x1f, 0x01, 0xac,
	0x3e, 0xa0, 0x71, 0xfa, 0x67, 0x5d, 0x16, 0x0e, 0xa9, 0x47, 0x83, 0x1b, 0x6d, 0x9d, 0xe1, 0x69,
	0x7f, 0xba, 0xe9, 0xa5, 0x37, 0x41, 0x59, 0x72, 0x68, 0x74, 0x71, 0xbc, 0xcf, 0x67, 0xdc, 0x87,
	0xde, 0xa0, 0x75, 0xbd, 0xc2, 0xfa, 0x8c, 0xa6, 0x51, 0xa1, 0xe9, 0x27, 0x49, 0x21, 0x55, 0x6a,
	0x6b, 0x1f, 0xb1, 0x62, 0xa9, 0x85, 0xaa, 0xcf, 0x84, 0x84, 0x05, 0xfe, 0xda, 0x69, 0x83, 0x5e,
	0xcd, 0xa1, 0x3a, 0xa4, 0xd9, 0xdf, 0x01, 0x24, 0x6a, 0xd4, 0xc6, 0xd9, 0x6e, 0x5c, 0x40, 0xf8,
	0x80, 0x7b, 0xee, 0x28, 0x51, 0x14, 0xd2, 0xc7, 0xca, 0xb6, 0x71, 0x45, 0xe9, 0x98, 0xec, 0x58,
	0x1d, 0x52, 0x91, 0xc3, 0x8b, 0x3e, 0xb4, 0xb7, 0x06, 0x2d, 0x36, 0x8e, 0x9b, 0x5b, 0xaa, 0x29,
	0x2c, 0xbe, 0x81, 0xb8, 0xd8, 0x18, 0xc4, 0x2d, 0xd5, 0xf8, 0xb5, 0x18, 0x00, 0x3a, 0xd5, 0x8d,
	0x76, 0xba, 0xa8, 0x3f, 0xdd, 0x72, 0xc3, 0x89, 0x1a, 0x00, 0x3a, 0x2d, 0x0d, 0x16, 0x0e, 0xab,
	0xf7, 0x8e, 0xb5, 0x1e, 0xaa, 0x01, 0x18, 0xed, 0xed, 0x72, 0xbc, 0xb7, 0xd9, 0x5f, 0x21, 0x3c,
	0x3f, 0xdd, 0xba, 0xe1, 0xa5, 0x31, 0xbf, 0xf4, 0x35, 0x80, 0xae, 0xb0, 0x21, 0xda, 0xd0, 0xf4,
	0x14, 0x8c, 0x90, 0x27, 0x68, 0x0c, 0xff, 0x93, 0x46, 0xdf, 0xc1, 0xfc, 0xc4, 0x39, 0x46, 0x24,
	0x44, 0x27, 0x24, 0x88, 0x2b, 0x80, 0xf2, 0x60, 0x4e, 0xc4, 0x10, 0x2d, 0xfe, 0x0b, 0xbf, 0xbe,
	0x47, 0xd3, 0x52, 0xa3, 0x12, 0x91, 0x41, 0x52, 0xb6, 0xdb, 0x3b, 0xdd, 0xf0, 0x9d, 0x96, 0xa7,
	0x90, 0xa8, 0x13, 0x8c, 0x9e, 0xb7, 0xbb, 0xe6, 0x21, 0x2c, 0xd5, 0x6c, 0x77, 0x3d, 0xd8, 0x54,
	0xcc, 0xc5, 0xbd, 0x4d, 0xbd, 0x81, 0xf5, 0xf1, 0xbb, 0x24, 0x7a, 0xef, 0x3b, 0xb1, 0x9a, 0xa0,
	0x4c, 0x98, 0x73, 0xb8, 0xed, 0x1c, 0x56, 0x72, 0xd5, 0x13, 0x76, 0x00, 0x88, 0xf8, 0xc1, 0x8f,
	0x3e, 0xb2, 0x09, 0x25, 0x7c, 0xcb, 0x14, 0x26, 0x5b, 0xdc, 0x4d, 0x7c, 0x47, 0x3e, 0xe7, 0xd2,
	0x33, 0x9c, 0x7a, 0x1b, 0xc6, 0xcf, 0x4b, 0xba, 0xe6, 0x8b, 0x27, 0x68, 0xf6, 0xe7, 0x0c, 0xa2,
	0xef, 0x0d, 0xe9, 0x7f, 0x2a, 0xde, 0x73, 0xca, 0x66, 0x4f, 0x52, 0x36, 0xa2, 0x26, 0x3c, 0xa5,
	0xe6, 0x68, 0xaa, 0xf3, 0xff, 0x35, 0x55, 0xf2, 0xc3, 0x72, 0x58, 0xfb, 0xcf, 0x7e, 0x95, 0xbd,
	0xb8, 0xcf, 0x0f, 0xd8, 0xb9, 0xc6, 0x7a, 0xf4, 0xc4, 0xc7, 0x6a, 0x82, 0x8e, 0xe4, 0xb4, 0x38,
	0x91, 0xd3, 0x25, 0x44, 0xe4, 0xcc, 0xa4, 0x73, 0xfa, 0x99, 0x4f, 0x88, 0x89, 0x3b, 0xdc, 0x14,
	0xcd, 0xad, 0x69, 0x4b, 0xb4, 0x56, 0x37, 0x1b, 0xe6, 0x7b, 0xa9, 0xa6, 0x30, 0xaf, 0xb1, 0xdf,
	0x1a, 0x09, 0xfe, 0xcd, 0x7d, 0x9a, 0x2d, 0x20, 0xfa, 0xb8, 0xed, 0xdc, 0xfe, 0xbb, 0xc5, 0x4f,
	0x11, 0xff, 0x89, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x0c, 0xd0, 0x3b, 0x5c, 0x07, 0x00,
	0x00,
}
