// Code generated by protoc-gen-go.
// source: grpc/interceptors_test.proto
// DO NOT EDIT!

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc/interceptors_test.proto

It has these top-level messages:
	Time
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Time struct {
	Time             *int64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Time) Reset()                    { *m = Time{} }
func (m *Time) String() string            { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()               {}
func (*Time) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Time) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Time)(nil), "Time")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion3

// Client API for InterceptorTest service

type InterceptorTestClient interface {
	// Sleep for the given amount of time, and return the amount of time slept.
	Chill(ctx context.Context, in *Time, opts ...grpc1.CallOption) (*Time, error)
}

type interceptorTestClient struct {
	cc *grpc1.ClientConn
}

func NewInterceptorTestClient(cc *grpc1.ClientConn) InterceptorTestClient {
	return &interceptorTestClient{cc}
}

func (c *interceptorTestClient) Chill(ctx context.Context, in *Time, opts ...grpc1.CallOption) (*Time, error) {
	out := new(Time)
	err := grpc1.Invoke(ctx, "/InterceptorTest/Chill", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InterceptorTest service

type InterceptorTestServer interface {
	// Sleep for the given amount of time, and return the amount of time slept.
	Chill(context.Context, *Time) (*Time, error)
}

func RegisterInterceptorTestServer(s *grpc1.Server, srv InterceptorTestServer) {
	s.RegisterService(&_InterceptorTest_serviceDesc, srv)
}

func _InterceptorTest_Chill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Time)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptorTestServer).Chill(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InterceptorTest/Chill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptorTestServer).Chill(ctx, req.(*Time))
	}
	return interceptor(ctx, in, info, handler)
}

var _InterceptorTest_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "InterceptorTest",
	HandlerType: (*InterceptorTestServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "Chill",
			Handler:    _InterceptorTest_Chill_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("grpc/interceptors_test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x2f, 0x2a, 0x48,
	0xd6, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0x4a, 0x4e, 0x2d, 0x28, 0xc9, 0x2f, 0x2a, 0x8e, 0x2f, 0x49,
	0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x12, 0xe1, 0x62, 0x09, 0xc9, 0xcc, 0x4d,
	0x15, 0xe2, 0xe1, 0x62, 0x29, 0x01, 0xd2, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x46, 0x5a, 0x5c,
	0xfc, 0x9e, 0x08, 0x0d, 0x21, 0x40, 0xe5, 0x42, 0xe2, 0x5c, 0xac, 0xce, 0x19, 0x99, 0x39, 0x39,
	0x42, 0xac, 0x7a, 0x20, 0x0d, 0x52, 0x10, 0x4a, 0x89, 0xc1, 0x89, 0x2d, 0x8a, 0x05, 0x64, 0x03,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x19, 0x2d, 0x5d, 0x68, 0x00, 0x00, 0x00,
}
