// Code generated by protoc-gen-go.
// source: publisher.proto
// DO NOT EDIT!

/*
Package publisher is a generated protocol buffer package.

It is generated from these files:
	publisher.proto

It has these top-level messages:
	Request
	Result
	Log
	MultipleRequest
	Empty
*/
package publisher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Der              []byte  `protobuf:"bytes,1,opt,name=der" json:"der,omitempty"`
	LogURL           *string `protobuf:"bytes,2,opt,name=LogURL,json=logURL" json:"LogURL,omitempty"`
	LogPublicKey     *string `protobuf:"bytes,3,opt,name=LogPublicKey,json=logPublicKey" json:"LogPublicKey,omitempty"`
	Precert          *bool   `protobuf:"varint,4,opt,name=precert" json:"precert,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetDer() []byte {
	if m != nil {
		return m.Der
	}
	return nil
}

func (m *Request) GetLogURL() string {
	if m != nil && m.LogURL != nil {
		return *m.LogURL
	}
	return ""
}

func (m *Request) GetLogPublicKey() string {
	if m != nil && m.LogPublicKey != nil {
		return *m.LogPublicKey
	}
	return ""
}

func (m *Request) GetPrecert() bool {
	if m != nil && m.Precert != nil {
		return *m.Precert
	}
	return false
}

type Result struct {
	Sct              []byte `protobuf:"bytes,1,opt,name=sct" json:"sct,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Result) GetSct() []byte {
	if m != nil {
		return m.Sct
	}
	return nil
}

type Log struct {
	URL              *string `protobuf:"bytes,1,opt,name=URL,json=uRL" json:"URL,omitempty"`
	PublicKey        *string `protobuf:"bytes,2,opt,name=PublicKey,json=publicKey" json:"PublicKey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Log) GetURL() string {
	if m != nil && m.URL != nil {
		return *m.URL
	}
	return ""
}

func (m *Log) GetPublicKey() string {
	if m != nil && m.PublicKey != nil {
		return *m.PublicKey
	}
	return ""
}

type MultipleRequest struct {
	Cert             []byte `protobuf:"bytes,1,opt,name=cert" json:"cert,omitempty"`
	Logs             []*Log `protobuf:"bytes,2,rep,name=logs" json:"logs,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MultipleRequest) Reset()                    { *m = MultipleRequest{} }
func (m *MultipleRequest) String() string            { return proto.CompactTextString(m) }
func (*MultipleRequest) ProtoMessage()               {}
func (*MultipleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MultipleRequest) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *MultipleRequest) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Empty struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Result)(nil), "Result")
	proto.RegisterType((*Log)(nil), "Log")
	proto.RegisterType((*MultipleRequest)(nil), "MultipleRequest")
	proto.RegisterType((*Empty)(nil), "Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Publisher service

type PublisherClient interface {
	SubmitToCT(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error)
	SubmitToSingleCT(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error)
	SubmitToSingleCTWithResult(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
	SubmitToMultipleCT(ctx context.Context, in *MultipleRequest, opts ...grpc.CallOption) (*Empty, error)
}

type publisherClient struct {
	cc *grpc.ClientConn
}

func NewPublisherClient(cc *grpc.ClientConn) PublisherClient {
	return &publisherClient{cc}
}

func (c *publisherClient) SubmitToCT(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/Publisher/SubmitToCT", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) SubmitToSingleCT(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/Publisher/SubmitToSingleCT", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) SubmitToSingleCTWithResult(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/Publisher/SubmitToSingleCTWithResult", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) SubmitToMultipleCT(ctx context.Context, in *MultipleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/Publisher/SubmitToMultipleCT", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Publisher service

type PublisherServer interface {
	SubmitToCT(context.Context, *Request) (*Empty, error)
	SubmitToSingleCT(context.Context, *Request) (*Empty, error)
	SubmitToSingleCTWithResult(context.Context, *Request) (*Result, error)
	SubmitToMultipleCT(context.Context, *MultipleRequest) (*Empty, error)
}

func RegisterPublisherServer(s *grpc.Server, srv PublisherServer) {
	s.RegisterService(&_Publisher_serviceDesc, srv)
}

func _Publisher_SubmitToCT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).SubmitToCT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Publisher/SubmitToCT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).SubmitToCT(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_SubmitToSingleCT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).SubmitToSingleCT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Publisher/SubmitToSingleCT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).SubmitToSingleCT(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_SubmitToSingleCTWithResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).SubmitToSingleCTWithResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Publisher/SubmitToSingleCTWithResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).SubmitToSingleCTWithResult(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_SubmitToMultipleCT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultipleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).SubmitToMultipleCT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Publisher/SubmitToMultipleCT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).SubmitToMultipleCT(ctx, req.(*MultipleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Publisher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Publisher",
	HandlerType: (*PublisherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitToCT",
			Handler:    _Publisher_SubmitToCT_Handler,
		},
		{
			MethodName: "SubmitToSingleCT",
			Handler:    _Publisher_SubmitToSingleCT_Handler,
		},
		{
			MethodName: "SubmitToSingleCTWithResult",
			Handler:    _Publisher_SubmitToSingleCTWithResult_Handler,
		},
		{
			MethodName: "SubmitToMultipleCT",
			Handler:    _Publisher_SubmitToMultipleCT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publisher.proto",
}

func init() { proto.RegisterFile("publisher.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x6b, 0xfb, 0x30,
	0x10, 0xc5, 0xe3, 0xd8, 0x7f, 0x3b, 0xb9, 0x7f, 0x20, 0xe1, 0x86, 0x22, 0x42, 0x07, 0xa3, 0xa1,
	0x78, 0x32, 0x6d, 0xa0, 0x73, 0x87, 0xd0, 0xa9, 0x2a, 0x14, 0x25, 0xa5, 0x7b, 0x5c, 0xa1, 0x18,
	0x94, 0x4a, 0xb1, 0xa4, 0x21, 0x5f, 0xad, 0x9f, 0xae, 0x58, 0x89, 0x70, 0x09, 0x74, 0xd3, 0xbd,
	0x7b, 0xf7, 0x7e, 0xba, 0x83, 0xb9, 0xf1, 0x3b, 0xd5, 0xda, 0xbd, 0xe8, 0x6a, 0xd3, 0x69, 0xa7,
	0xe9, 0x11, 0x0a, 0x2e, 0x8e, 0x5e, 0x58, 0x87, 0x0b, 0x48, 0x3f, 0x45, 0x47, 0x92, 0x32, 0xa9,
	0x66, 0xbc, 0x7f, 0xe2, 0x0d, 0xe4, 0x4c, 0xcb, 0x77, 0xce, 0xc8, 0xb8, 0x4c, 0xaa, 0x29, 0xcf,
	0x55, 0xa8, 0x90, 0xc2, 0x8c, 0x69, 0xf9, 0xd6, 0x47, 0x35, 0x2f, 0xe2, 0x44, 0xd2, 0xd0, 0x9d,
	0xa9, 0x5f, 0x1a, 0x12, 0x28, 0x4c, 0x27, 0x1a, 0xd1, 0x39, 0x92, 0x95, 0x49, 0x35, 0xe1, 0xb1,
	0xa4, 0x4b, 0xc8, 0xb9, 0xb0, 0x5e, 0x05, 0xa2, 0x6d, 0x5c, 0x24, 0xda, 0xc6, 0xd1, 0x47, 0x48,
	0x99, 0x96, 0x7d, 0xa3, 0xa7, 0x26, 0x21, 0x37, 0xf5, 0x9c, 0xe1, 0x2d, 0x4c, 0x07, 0xde, 0xf9,
	0x37, 0x53, 0x13, 0x05, 0xfa, 0x04, 0xf3, 0x57, 0xaf, 0x5c, 0x6b, 0x94, 0x88, 0xdb, 0x20, 0x64,
	0x01, 0x7e, 0x0e, 0x0f, 0x6f, 0x24, 0x90, 0x29, 0x2d, 0x2d, 0x19, 0x97, 0x69, 0xf5, 0x7f, 0x95,
	0xd5, 0x4c, 0x4b, 0x1e, 0x14, 0x5a, 0xc0, 0xbf, 0xe7, 0x83, 0x71, 0xa7, 0xd5, 0x77, 0x72, 0x01,
	0xf5, 0x37, 0xc2, 0x12, 0x60, 0xe3, 0x77, 0x87, 0xd6, 0x6d, 0xf5, 0x7a, 0x8b, 0x93, 0xfa, 0x12,
	0xbe, 0xcc, 0xeb, 0xe0, 0xa6, 0x23, 0xbc, 0x83, 0x45, 0x74, 0x6c, 0xda, 0x2f, 0xa9, 0xc4, 0x1f,
	0xbe, 0x07, 0x58, 0x5e, 0xfb, 0x3e, 0x5a, 0xb7, 0xbf, 0x1c, 0x62, 0x98, 0x28, 0xea, 0xb3, 0x44,
	0x47, 0x78, 0x0f, 0x18, 0x47, 0xe2, 0x72, 0xeb, 0x2d, 0x2e, 0xea, 0xab, 0x4d, 0x07, 0xc8, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0xef, 0x57, 0xbf, 0xde, 0x01, 0x00, 0x00,
}
