// Code generated by "stringer -type=FeatureFlag"; DO NOT EDIT.

package features

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unused-0]
	_ = x[PrecertificateRevocation-1]
	_ = x[StripDefaultSchemePort-2]
	_ = x[CAAValidationMethods-3]
	_ = x[CAAAccountURI-4]
	_ = x[EnforceMultiVA-5]
	_ = x[MultiVAFullResults-6]
	_ = x[MandatoryPOSTAsGET-7]
	_ = x[AllowV1Registration-8]
	_ = x[V1DisableNewValidations-9]
	_ = x[StoreIssuerInfo-10]
	_ = x[StoreRevokerInfo-11]
	_ = x[RestrictRSAKeySizes-12]
	_ = x[FasterNewOrdersRateLimit-13]
	_ = x[NonCFSSLSigner-14]
	_ = x[ECDSAForAll-15]
}

const _FeatureFlag_name = "unusedPrecertificateRevocationStripDefaultSchemePortCAAValidationMethodsCAAAccountURIEnforceMultiVAMultiVAFullResultsMandatoryPOSTAsGETAllowV1RegistrationV1DisableNewValidationsStoreIssuerInfoStoreRevokerInfoRestrictRSAKeySizesFasterNewOrdersRateLimitNonCFSSLSignerECDSAForAll"

var _FeatureFlag_index = [...]uint16{0, 6, 30, 52, 72, 85, 99, 117, 135, 154, 177, 192, 208, 227, 251, 265, 276}

func (i FeatureFlag) String() string {
	if i < 0 || i >= FeatureFlag(len(_FeatureFlag_index)-1) {
		return "FeatureFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FeatureFlag_name[_FeatureFlag_index[i]:_FeatureFlag_index[i+1]]
}
