// Code generated by protoc-gen-go.
// source: caaChecker.proto
// DO NOT EDIT!

/*
Package caaChecker is a generated protocol buffer package.

It is generated from these files:
	caaChecker.proto

It has these top-level messages:
	Domain
	Valid
*/
package caaChecker

import proto "github.com/letsencrypt/boulder/Godeps/_workspace/src/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "github.com/letsencrypt/boulder/Godeps/_workspace/src/golang.org/x/net/context"
	grpc "github.com/letsencrypt/boulder/Godeps/_workspace/src/google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Domain struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Domain) Reset()                    { *m = Domain{} }
func (m *Domain) String() string            { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()               {}
func (*Domain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Valid struct {
	Present bool `protobuf:"varint,1,opt,name=present" json:"present,omitempty"`
	Valid   bool `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *Valid) Reset()                    { *m = Valid{} }
func (m *Valid) String() string            { return proto.CompactTextString(m) }
func (*Valid) ProtoMessage()               {}
func (*Valid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Domain)(nil), "Domain")
	proto.RegisterType((*Valid)(nil), "Valid")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for CAAChecker service

type CAACheckerClient interface {
	ValidForIssuance(ctx context.Context, in *Domain, opts ...grpc.CallOption) (*Valid, error)
}

type cAACheckerClient struct {
	cc *grpc.ClientConn
}

func NewCAACheckerClient(cc *grpc.ClientConn) CAACheckerClient {
	return &cAACheckerClient{cc}
}

func (c *cAACheckerClient) ValidForIssuance(ctx context.Context, in *Domain, opts ...grpc.CallOption) (*Valid, error) {
	out := new(Valid)
	err := grpc.Invoke(ctx, "/CAAChecker/ValidForIssuance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CAAChecker service

type CAACheckerServer interface {
	ValidForIssuance(context.Context, *Domain) (*Valid, error)
}

func RegisterCAACheckerServer(s *grpc.Server, srv CAACheckerServer) {
	s.RegisterService(&_CAAChecker_serviceDesc, srv)
}

func _CAAChecker_ValidForIssuance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Domain)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CAACheckerServer).ValidForIssuance(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _CAAChecker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CAAChecker",
	HandlerType: (*CAACheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidForIssuance",
			Handler:    _CAAChecker_ValidForIssuance_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x4e, 0x4c, 0x74,
	0xce, 0x48, 0x4d, 0xce, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe1, 0x62,
	0x73, 0xc9, 0xcf, 0x4d, 0xcc, 0xcc, 0x13, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xcc, 0xb9, 0x58, 0xc3, 0x12, 0x73, 0x32, 0x53,
	0x84, 0x24, 0xb8, 0xd8, 0x0b, 0x8a, 0x52, 0x8b, 0x53, 0xf3, 0x4a, 0xc0, 0xf2, 0x1c, 0x41, 0x30,
	0xae, 0x90, 0x08, 0x17, 0x6b, 0x19, 0x48, 0x89, 0x04, 0x13, 0x58, 0x1c, 0xc2, 0x31, 0x32, 0xe6,
	0xe2, 0x72, 0x76, 0x74, 0x84, 0x5a, 0x25, 0xa4, 0xca, 0x25, 0x00, 0x36, 0xc6, 0x2d, 0xbf, 0xc8,
	0xb3, 0xb8, 0xb8, 0x34, 0x31, 0x2f, 0x39, 0x55, 0x88, 0x5d, 0x0f, 0x62, 0xaf, 0x14, 0x9b, 0x1e,
	0x58, 0x4e, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x24, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea,
	0x9a, 0x8c, 0x7a, 0xa6, 0x00, 0x00, 0x00,
}
