syntax = "proto3";

package mtcb;
option go_package = "github.com/letsencrypt/boulder/mtcb/proto";

// MTCB constructs already-issued MTCs from database and log data.
service MTCB {
  // StandaloneReady returns whether a given TBSCertificateLogEntry has sufficient signatures
  // for a standalone certificate to be built.
  rpc StandaloneReady(StandaloneReadyRequest) returns (StandaloneReadyResponse) {}
  // GetStandalone returns a standalone certificate.
  rpc GetStandalone(StandaloneRequest) returns (StandaloneResponse) {}
  // GetLandmarkRelative returns a landmark-relative certificate.
  rpc GetLandmarkRelative(LandmarkRelativeRequest) returns (LandmarkRelativeResponse) {}
}

message StandaloneReadyRequest {
  // Next unused field number: 4
  string mtcLogID = 1;
  uint64 mtcSerialNumber = 2;
  int64 mtcSubtreeID = 3;
}

message StandaloneReadyResponse {
  // Next unused field number: 2
  bool ready = 1;
}

message StandaloneRequest {
  // Next unused field number: 4
  string mtcLogID = 1;
  uint64 mtcSerialNumber = 2;
  int64 mtcSubtreeID = 3;
}

message StandaloneResponse {
  // Next unused field number: 2
  bytes certDER = 1;
}

message LandmarkRelativeRequest {
  // Next unused field number: 3
  string mtcLogID = 1;
  uint64 serial = 2;
}

message LandmarkRelativeResponse {
  // Next unused field number: 3
  bytes certDER = 1;
  bytes certPropList = 2;
}
