# Build and publish containers for this release
# see also container-build.yml

name: Container Release

on:
  push:
    tags:
      - release-*

jobs:
  push-container:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: test/ct-test-srv/Dockerfile
            image: ghcr.io/letsencrypt/ct-test-srv
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: docker buildx build . -f "${{ matrix.dockerfile }}" -t "${{ matrix.image }}:${{ github.ref_name }}"

      - name: login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push
        run: docker push "${{ matrix.image }}:${{ github.ref_name }}"
