name: Govulncheck

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - release-branch-*
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  b:
    runs-on: ubuntu-20.04
    strategy:
      # When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
      fail-fast: false
      matrix:
        BOULDER_TOOLS_TAG:
          - go1.20.5_2023-06-20
          - go1.21rc2_2023-06-21

    env:
      # This sets the docker image tag for the boulder-tools repository to
      # use in tests. It will be set appropriately for each tag in the list
      # defined in the matrix.
      BOULDER_TOOLS_TAG: ${{ matrix.BOULDER_TOOLS_TAG }}

    steps:
      # Print the env variable being used to pull the docker image. For
      # informational use.
      - name: Print BOULDER_TOOLS_TAG
        run: echo "Using BOULDER_TOOLS_TAG ${BOULDER_TOOLS_TAG}"

      # Enable https://github.com/golang/go/wiki/LoopvarExperiment if we're on
      # go1.21rc2 or higher. This experiment value is unknown in lower versions.
      - if: startsWith(matrix.BOULDER_TOOLS_TAG, 'go1.21')
        run: echo "GOEXPERIMENT=loopvar" >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@v3

      - id: Run govulncheck
        uses: golang/govulncheck-action@v0.1.0
